/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as CraftsIndexRouteImport } from './routes/crafts/index'
import { Route as DemoTaggerIndexRouteImport } from './routes/demo/tagger/index'
import { Route as AppsSlugIndexRouteImport } from './routes/apps/$slug/index'
import { Route as AppsSlugSupportRouteImport } from './routes/apps/$slug/support'
import { Route as AppsSlugPrivacyRouteImport } from './routes/apps/$slug/privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsIndexRoute = CraftsIndexRouteImport.update({
  id: '/crafts/',
  path: '/crafts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTaggerIndexRoute = DemoTaggerIndexRouteImport.update({
  id: '/demo/tagger/',
  path: '/demo/tagger/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugIndexRoute = AppsSlugIndexRouteImport.update({
  id: '/apps/$slug/',
  path: '/apps/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugSupportRoute = AppsSlugSupportRouteImport.update({
  id: '/apps/$slug/support',
  path: '/apps/$slug/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugPrivacyRoute = AppsSlugPrivacyRouteImport.update({
  id: '/apps/$slug/privacy',
  path: '/apps/$slug/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crafts': typeof CraftsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/apps/$slug/privacy': typeof AppsSlugPrivacyRoute
  '/apps/$slug/support': typeof AppsSlugSupportRoute
  '/apps/$slug': typeof AppsSlugIndexRoute
  '/demo/tagger': typeof DemoTaggerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crafts': typeof CraftsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/apps/$slug/privacy': typeof AppsSlugPrivacyRoute
  '/apps/$slug/support': typeof AppsSlugSupportRoute
  '/apps/$slug': typeof AppsSlugIndexRoute
  '/demo/tagger': typeof DemoTaggerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crafts/': typeof CraftsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/apps/$slug/privacy': typeof AppsSlugPrivacyRoute
  '/apps/$slug/support': typeof AppsSlugSupportRoute
  '/apps/$slug/': typeof AppsSlugIndexRoute
  '/demo/tagger/': typeof DemoTaggerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crafts'
    | '/projects'
    | '/apps/$slug/privacy'
    | '/apps/$slug/support'
    | '/apps/$slug'
    | '/demo/tagger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crafts'
    | '/projects'
    | '/apps/$slug/privacy'
    | '/apps/$slug/support'
    | '/apps/$slug'
    | '/demo/tagger'
  id:
    | '__root__'
    | '/'
    | '/crafts/'
    | '/projects/'
    | '/apps/$slug/privacy'
    | '/apps/$slug/support'
    | '/apps/$slug/'
    | '/demo/tagger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CraftsIndexRoute: typeof CraftsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  AppsSlugPrivacyRoute: typeof AppsSlugPrivacyRoute
  AppsSlugSupportRoute: typeof AppsSlugSupportRoute
  AppsSlugIndexRoute: typeof AppsSlugIndexRoute
  DemoTaggerIndexRoute: typeof DemoTaggerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafts/': {
      id: '/crafts/'
      path: '/crafts'
      fullPath: '/crafts'
      preLoaderRoute: typeof CraftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tagger/': {
      id: '/demo/tagger/'
      path: '/demo/tagger'
      fullPath: '/demo/tagger'
      preLoaderRoute: typeof DemoTaggerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug/': {
      id: '/apps/$slug/'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug/support': {
      id: '/apps/$slug/support'
      path: '/apps/$slug/support'
      fullPath: '/apps/$slug/support'
      preLoaderRoute: typeof AppsSlugSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug/privacy': {
      id: '/apps/$slug/privacy'
      path: '/apps/$slug/privacy'
      fullPath: '/apps/$slug/privacy'
      preLoaderRoute: typeof AppsSlugPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CraftsIndexRoute: CraftsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  AppsSlugPrivacyRoute: AppsSlugPrivacyRoute,
  AppsSlugSupportRoute: AppsSlugSupportRoute,
  AppsSlugIndexRoute: AppsSlugIndexRoute,
  DemoTaggerIndexRoute: DemoTaggerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
